# Dataset
copy_dataset: true
split_ratio: [0.8, 0.1, 0.1]
raw_data_dir: "./dataset/_raw/"
split_data_dir: "./dataset/"  # [train, val, test] dirs
dloader_workers: 6

# ImageNet Normalization values
mean: [0.485, 0.456, 0.406]
std: [0.229, 0.224, 0.225]

# Model
model_type: mobilenet_v3_large
input_size: [224, 224]
add_softmax: false

# Augmentation
augmentations: false          # use advanced albumentations
scale_range: [0.75, 1.0]

# Training
batch_size: 50
num_epochs: 20
learning_rate: 0.0001
optimizer_name: adam
train_deep: true
scheduler: reduce_on_plateau  # options: reduce_on_plateau, step, cosine
scheduler_patience: 2         # epochs with no improvement before reducing LR
scheduler_factor: 0.5         # LR reduction factor
early_stopping_patience: 4    # epochs with no improvement before stopping
checkpoints_dir: checkpoints/

# List of available models
model_list:
  - resnet18
  - resnet50
  - alexnet
  - vgg11_bn
  - squeezenet
  - densenet121
  - inception_v3
  - mobilenet_v2
  - mobilenet_v3_large
  - regnet_y_16gf
  - efficientnet_v2_s
  - efficientnet_v2_m
  - convnext_base
  - swin_v2_b